# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mariadb:
        image: mariadb:latest
        container_name: "${APP_NAME}-mariadb"
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
        networks:
            - network-microservice
        volumes:
            - mariadb-data:/var/lib/mysql
            - mariadb-config:/etc/mysql

networks:
    network-microservice:
        external: true

volumes:
    mariadb-data:
    mariadb-config:

