# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mariadb:
        image: mysql:8.0-oracle
        container_name: "${APP_NAME}-mariadb"
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - network-microservice
        volumes:
            - mysql-data:/var/lib/mysql
            - mysql-config:/etc/mysql

networks:
    network-microservice:
        external: true

volumes:
    mysql-data:
    mysql-config:

